### ISSUE TITLE
Compression reads after supplied buffer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ShaneWF/wflz#2]
```
I'm adding a unit test to Squash which puts a protected page of memory 
immediately after the uncompressed data, and it causes wfLZ to fail.

Test case (modified for use outside of Squash) attached.  Backtrace:

Program received signal SIGSEGV, Segmentation fault.
0x0000000000401806 in wfLZ_MemCmp_i (a=0x605ffd, b=0x605c1b, count=4, maxLen=7) 
at wfLZ.c:699
699     if( *a != *b )
Missing separate debuginfos, use: debuginfo-install glibc-2.20-8.fc21.x86_64
(gdb) bt
#0  0x0000000000401806 in wfLZ_MemCmp_i (a=0x605ffd, b=0x605c1b, count=4, 
maxLen=7) at wfLZ.c:699
#1  0x000000000040188f in wfLZ_MemCmp_i (a=0x605ffd, b=0x605c1b, count=0, 
maxLen=7) at wfLZ.c:706
#2  0x00000000004018be in wfLZ_MemCmp (a=0x605ff9 "sapien.", 
    b=0x605c17 "sapien, ut dignissim elit. Proin eleifend arcu tempus, semper erat et, accumsan erat. Praesent vulputate diam mi, eget mollis leo pellentesque eget. Aliquam eu tortor posuere, posuere velit sed, susci"..., maxLen=7) at wfLZ.c:711
#3  0x0000000000400c0b in wfLZ_CompressFast (
    in=0x60555b "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vulputate lectus nisl, vitae ultricies justo dictum nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia C"..., inSize=2725, out=0x607020 "", workMem=0x7ffff7f55010 "", swapEndian=0) at wfLZ.c:223
#4  0x0000000000400963 in main (argc=1, argv=0x7fffffffdeb8) at test.c:105
```

Original issue reported on code.google.com by `nem...@gmail.com` on 9 Mar 2015 at 5:08

Attachments:
- [test.c](https://storage.googleapis.com/google-code-attachments/wflz/issue-2/comment-0/test.c)

**Comment by nemequ** [comment]
The latest version passes all my tests, thanks!
